### ISSUE TITLE
Include old version / transfer to davelab6

### ISSUE THREAD

**Issue by davelab6** [googlefonts/comfortaa#10]
- [x] I found https://github.com/ongardie/Comfortaa :) I guess it would be nice to have the old v1 version in this repo in `/old` :)

- [x] I'd like to transfer this to /googlefonts and to get it there, please transfer it to me (in https://github.com/alexeiva/comfortaa/settings)

**Comment by alexeiva** [comment]
this repo is now ready to be transferred

**Comment by davelab6** [comment]
I think you have to do it, on the

**Comment by alexeiva** [comment]
I see. I aborted your transfer, and started a new one.

**Comment by davelab6** [comment]
Thanks!
